export const GET_SPENDING_CATEGORIES_BEGIN = 'GET_SPENDING_CATEGORIES_BEGIN';
export const GET_SPENDING_CATEGORIES_SUCCESS = 'GET_SPENDING_CATEGORIES_SUCCESS';
export const GET_SPENDING_CATEGORIES_FAILED = 'GET_SPENDING_CATEGORIES_FAILED';

export const ADD_SPENDING_CATEGORY_BEGIN = 'ADD_SPENDING_CATEGORY_BEGIN';
export const ADD_SPENDING_CATEGORY_SUCCESS = 'ADD_SPENDING_CATEGORY_SUCCESS';
export const ADD_SPENDING_CATEGORY_FAILED = 'ADD_SPENDING_CATEGORY_FAILED';

export const EDIT_SPENDING_CATEGORY_BEGIN = 'EDIT_SPENDING_CATEGORY_BEGIN';
export const EDIT_SPENDING_CATEGORY_SUCCESS = 'EDIT_SPENDING_CATEGORY_SUCCESS';
export const EDIT_SPENDING_CATEGORY_FAILED = 'EDIT_SPENDING_CATEGORY_FAILED';

export const DELETE_SPENDING_CATEGORY_BEGIN = 'DELETE_SPENDING_CATEGORY_BEGIN';
export const DELETE_SPENDING_CATEGORY_SUCCESS = 'DELETE_SPENDING_CATEGORY_SUCCESS';
export const DELETE_SPENDING_CATEGORY_FAILED = 'DELETE_SPENDING_CATEGORY_FAILED';