export const GET_SPENDINGS_BEGIN = 'GET_SPENDINGS_BEGIN';
export const GET_SPENDINGS_SUCCESS = 'GET_SPENDINGS_SUCCESS';
export const GET_SPENDINGS_FAILED = 'GET_SPENDINGS_FAILED';

export const ADD_SPENDING_BEGIN = 'ADD_SPENDING_BEGIN';
export const ADD_SPENDING_SUCCESS = 'ADD_SPENDING_SUCCESS';
export const ADD_SPENDING_FAILED = 'ADD_SPENDING_FAILED';

export const EDIT_SPENDING_BEGIN = 'EDIT_SPENDING_BEGIN';
export const EDIT_SPENDING_SUCCESS = 'EDIT_SPENDING_SUCCESS';
export const EDIT_SPENDING_FAILED = 'EDIT_SPENDING_FAILED';

export const DELETE_SPENDING_BEGIN = 'DELETE_SPENDING_BEGIN';
export const DELETE_SPENDING_SUCCESS = 'DELETE_SPENDING_SUCCESS';
export const DELETE_SPENDING_FAILED = 'DELETE_SPENDING_FAILED';
