export const GET_USER_SETTINGS_BEGIN = 'GET_USER_SETTINGS_BEGIN';
export const GET_USER_SETTINGS_SUCCESS = 'GET_USER_SETTINGS_SUCCESS';
export const GET_USER_SETTINGS_FAILED = 'GET_USER_SETTINGS_FAILED';

export const SAVE_USER_SETTINGS_BEGIN = 'SAVE_USER_SETTINGS_BEGIN';
export const SAVE_USER_SETTINGS_SUCCESS = 'SAVE_USER_SETTINGS_SUCCESS';
export const SAVE_USER_SETTINGS_FAILED = 'SAVE_USER_SETTINGS_FAILED';
